/* Plain-English decoder copy for every taught field, reworked in the voice of the
   user-supplied "Loan Document Decoder Redesign" handoff (docdata.js) and
   accuracy-checked against TRID before approval. Each body = punchy definition +
   where-it-lives context + the shared fictional-sample note. `ASKS` feeds the
   decoder card's "Ask your lender" callout. Source references are unchanged from
   the previously reviewed corpus. */

const GROUPS = Object.freeze({
  'form-general-information': Object.freeze({
    why: 'It sits in General Information near the top of both forms so the paperwork can be matched to the right property and transaction.',
    reference: 'H24B page 1; H25B page 1; CFPB Guide to Forms v2.1 §§ 2.2.1 and 3.2.1; 12 CFR 1026.37(a)(4), (6)–(7), 1026.38(a)(3)(i), (vi)–(vii)',
  }),
  'le-general-information': Object.freeze({
    why: 'It sits in the Loan Estimate’s General Information so the estimate can be matched to the people applying.',
    reference: 'H24B page 1; CFPB Guide to Forms v2.1 § 2.2.1; 12 CFR 1026.37(a)(5)',
  }),
  'cd-general-information': Object.freeze({
    why: 'It sits in the Closing Disclosure’s General Information so the final paperwork can be matched to the parties and the closing file.',
    reference: 'H25B page 1; CFPB Guide to Forms v2.1 § 3.2.1; 12 CFR 1026.38(a)(3)(ii)–(v), (4), (5)(vi)',
  }),
  'loan-information': Object.freeze({
    why: 'It sits in General Information at the top of the form so you can identify the exact loan before digging into its terms.',
    reference: 'H24B page 1; H25B page 1; CFPB Guide to Forms v2.1 §§ 2.2.1 and 3.2.1; 12 CFR 1026.37(a)(8)–(12), 1026.38(a)(5)(i)–(v)',
  }),
  'le-rate-lock': Object.freeze({
    why: 'It sits in the Loan Estimate’s General Information and states whether the quoted rate is protected and until when.',
    reference: 'H24B page 1; CFPB Guide to Forms v2.1 § 2.2.1; 12 CFR 1026.37(a)(13)',
  }),
  'loan-terms': Object.freeze({
    why: 'It sits in the Loan Terms section on both forms — the table to compare line by line against the other document.',
    reference: 'H24B page 1; H25B page 1; CFPB Guide to Forms v2.1 §§ 2.2.2 and 3.2.2; 12 CFR 1026.37(b), 1026.38(b)',
  }),
  'projected-payments': Object.freeze({
    why: 'It sits in the Projected Payments table, which shows how your monthly housing cost is built and when it can change.',
    reference: 'H24B page 1; H25B page 1; CFPB Guide to Forms v2.1 §§ 2.2.3 and 3.2.3; 12 CFR 1026.37(c), 1026.38(c)',
  }),
  'le-costs-at-closing': Object.freeze({
    why: 'It sits in the Loan Estimate’s Costs at Closing summary, with the line-by-line detail on page 2.',
    reference: 'H24B page 1; CFPB Guide to Forms v2.1 § 2.2.4; 12 CFR 1026.37(d)',
  }),
  'cd-costs-at-closing': Object.freeze({
    why: 'It sits in the Closing Disclosure’s Costs at Closing summary, with the final line-by-line detail on page 2.',
    reference: 'H25B page 1; CFPB Guide to Forms v2.1 § 3.2.4; 12 CFR 1026.38(d)',
  }),
  'cost-item': Object.freeze({
    why: 'It sits in Closing Cost Details, the page-2 breakdown of every charge, credit, and service in the transaction.',
    reference: 'H24B page 2; H25B page 2; CFPB Guide to Forms v2.1 §§ 2.3.1–2.3.2 and 3.3.1–3.3.2; 12 CFR 1026.37(f)–(g), 1026.38(f)–(h)',
  }),
  'le-cost-total': Object.freeze({
    why: 'It sits on the Loan Estimate’s page 2 as a subtotal, showing how estimated charges group before they roll into cash to close.',
    reference: 'H24B page 2; CFPB Guide to Forms v2.1 §§ 2.3.1–2.3.3; 12 CFR 1026.37(f)–(h)',
  }),
  'cd-cost-total': Object.freeze({
    why: 'It sits on the Closing Disclosure’s page 2 as a subtotal, so you can trace final charges and who paid them.',
    reference: 'H25B page 2; CFPB Guide to Forms v2.1 §§ 3.3.1–3.3.2; 12 CFR 1026.38(f)–(h)',
  }),
  'payer-column': Object.freeze({
    why: 'It heads a column in Closing Cost Details — the layout that shows who paid each charge and when.',
    reference: 'H25B page 2; CFPB Guide to Forms v2.1 §§ 3.3.1–3.3.2; 12 CFR 1026.38(f)–(h)',
  }),
  'le-cash': Object.freeze({
    why: 'It sits in the Loan Estimate’s Calculating Cash to Close table, which builds up the money expected at closing.',
    reference: 'H24B page 2; CFPB Guide to Forms v2.1 § 2.3.3; 12 CFR 1026.37(h)',
  }),
  'cd-cash': Object.freeze({
    why: 'It sits in the Closing Disclosure’s Calculating Cash to Close table, which compares the estimate to the final figure line by line.',
    reference: 'H25B page 3; CFPB Guide to Forms v2.1 § 3.4.1; 12 CFR 1026.38(i)',
  }),
  'le-cash-total': Object.freeze({
    why: 'It appears twice — in the Costs at Closing summary and as the bottom line of Calculating Cash to Close — so you can trace how it was built.',
    reference: 'H24B pages 1–2; CFPB Guide to Forms v2.1 §§ 2.2.4 and 2.3.3; 12 CFR 1026.37(d), 1026.37(h)',
  }),
  'cd-cash-total': Object.freeze({
    why: 'It appears twice — in the Costs at Closing summary and as the bottom line of Calculating Cash to Close — so you can trace how it was built.',
    reference: 'H25B pages 1 and 3; CFPB Guide to Forms v2.1 §§ 3.2.4 and 3.4.1; 12 CFR 1026.38(d), 1026.38(i)',
  }),
  'le-comparison': Object.freeze({
    why: 'It sits in the Loan Estimate’s Comparisons section, built for lining up offers from different lenders.',
    reference: 'H24B page 3; CFPB Guide to Forms v2.1 § 2.4.2; 12 CFR 1026.37(l)',
  }),
  'shared-cost-measure': Object.freeze({
    why: 'It sits in the Loan Estimate’s Comparisons and the Closing Disclosure’s Loan Calculations, standard yardsticks for comparing loans.',
    reference: 'H24B page 3; H25B page 5; CFPB Guide to Forms v2.1 §§ 2.4.2 and 3.6.1; 12 CFR 1026.37(l), 1026.38(o)',
  }),
  'shared-loan-disclosure': Object.freeze({
    why: 'It sits in Other Considerations on the Loan Estimate and Loan Disclosures on the Closing Disclosure, because it can matter long after closing.',
    reference: 'H24B page 3; H25B page 4; CFPB Guide to Forms v2.1 §§ 2.4.3 and 3.5.1; 12 CFR 1026.37(m), 1026.38(l)',
  }),
  'shared-other-disclosure': Object.freeze({
    why: 'It sits in Other Considerations on the Loan Estimate and Other Disclosures on the Closing Disclosure, describing a right or future option you keep.',
    reference: 'H24B page 3; H25B page 5; CFPB Guide to Forms v2.1 §§ 2.4.3 and 3.6.2; 12 CFR 1026.37(m), 1026.38(p)',
  }),
  'le-other-consideration': Object.freeze({
    why: 'It sits in the Loan Estimate’s Other Considerations — policies worth understanding before you commit.',
    reference: 'H24B page 3; CFPB Guide to Forms v2.1 § 2.4.3; 12 CFR 1026.37(m)',
  }),
  'cd-loan-disclosure': Object.freeze({
    why: 'It sits in the Closing Disclosure’s Loan Disclosures — final contractual features of the mortgage you are signing.',
    reference: 'H25B page 4; CFPB Guide to Forms v2.1 § 3.5.1; 12 CFR 1026.38(l)',
  }),
  'le-contact': Object.freeze({
    why: 'It sits in the Loan Estimate’s Contact Information so you know exactly who is handling your application.',
    reference: 'H24B page 3; CFPB Guide to Forms v2.1 § 2.4.1; 12 CFR 1026.37(k)',
  }),
  'shared-lender-contact': Object.freeze({
    why: 'It sits in Contact Information on both forms so you can identify and reach the creditor behind the loan.',
    reference: 'H24B page 3; H25B page 5; CFPB Guide to Forms v2.1 §§ 2.4.1 and 3.6.3; 12 CFR 1026.37(k), 1026.38(r)',
  }),
  'cd-contact': Object.freeze({
    why: 'It sits in the Closing Disclosure’s Contact Information, listing every professional in the transaction with their license numbers.',
    reference: 'H25B page 5; CFPB Guide to Forms v2.1 § 3.6.3; 12 CFR 1026.38(r)',
  }),
  receipt: Object.freeze({
    why: 'It sits at the end of the form, and it documents delivery only — signing is not acceptance of the loan.',
    reference: 'H24B page 3; H25B page 5; CFPB Guide to Forms v2.1 §§ 2.4.5 and 3.6.4; 12 CFR 1026.37(n), 1026.38(s)',
  }),
  'borrower-transaction': Object.freeze({
    why: 'It sits in the borrower’s transaction summary on page 3, the ledger of everything you owe and everything already credited to you.',
    reference: 'H25B page 3; CFPB Guide to Forms v2.1 §§ 3.4.3–3.4.4; 12 CFR 1026.38(j)',
  }),
  'seller-transaction': Object.freeze({
    why: 'It sits in the seller’s transaction summary on page 3, the ledger that works out the seller’s proceeds from the sale.',
    reference: 'H25B page 3; CFPB Guide to Forms v2.1 §§ 3.4.3 and 3.4.5; 12 CFR 1026.38(k)',
  }),
  escrow: Object.freeze({
    why: 'It sits in the Escrow Account disclosure, which spells out how property costs are paid through — or outside — escrow.',
    reference: 'H25B page 4; CFPB Guide to Forms v2.1 § 3.5.3; 12 CFR 1026.38(l)(7)',
  }),
  'loan-calculation': Object.freeze({
    why: 'It sits in Loan Calculations, the federally defined cost measures computed from your final loan terms.',
    reference: 'H25B page 5; CFPB Guide to Forms v2.1 § 3.6.1; 12 CFR 1026.38(o)',
  }),
  'other-disclosure': Object.freeze({
    why: 'It sits in Other Disclosures, pointing you to important documents, legal consequences, and post-closing considerations.',
    reference: 'H25B page 5; CFPB Guide to Forms v2.1 § 3.6.2; 12 CFR 1026.38(p)',
  }),
  questions: Object.freeze({
    why: 'It sits on the Closing Disclosure so you know where to take questions and where to find CFPB help or file a complaint.',
    reference: 'H25B page 5; CFPB Guide to Forms v2.1 § 3.6; 12 CFR 1026.38(q)',
  }),
  'refi-property-value': Object.freeze({
    why: 'It sits in General Information on the refinance forms, where the property’s value stands in for a sale price that doesn’t exist.',
    reference: 'H24D page 1; H25E page 1; H25G page 1; CFPB Guide to Forms v2.1 §§ 2.2.1 and 3.2.1; 12 CFR 1026.37(a)(7)(ii), 1026.38(a)(3)(vii)(B)',
  }),
  'refi-payoffs': Object.freeze({
    why: 'It sits in the payoff tables the refinance forms use instead of a purchase ledger, routing the new loan to existing debts before any cash moves.',
    reference: 'H24D page 2; H25E page 3; H25G page 3; CFPB Guide to Forms v2.1 §§ 2.3.3 and 3.4.2; 12 CFR 1026.37(h)(2), 1026.38(e), 1026.38(t)(5)(vii)(B)',
  }),
});

const SAMPLE_NOTE = 'This fictional sample shows one transaction — your own numbers, terms, and providers will differ, so walk through your actual form with your lender or settlement professional.';

/* "Ask your lender" prompts, adapted from the user-supplied handoff copy. */
const ASKS = Object.freeze({
  'date-issued': 'How long are these terms good for, and when does my Closing Disclosure three-day review window start?',
  applicants: 'Is everyone listed here who should be on the loan?',
  property: 'Is the full legal address correct?',
  'sale-price': 'Does this match my purchase contract?',
  'loan-term': 'Would a shorter term make sense for my situation?',
  product: 'Are there other rate structures I should compare?',
  'loan-type': 'Do I qualify for FHA, VA, or other program alternatives?',
  'rate-lock': 'What does it cost to lock my rate today, and until when?',
  'loan-amount': 'Why is this amount different from the sale price?',
  'interest-rate': 'Does this match my rate lock agreement?',
  'monthly-principal-interest': 'What will my total monthly payment be with taxes and insurance?',
  'prepayment-penalty': 'Can I get this loan without a prepayment penalty?',
  'projected-mortgage-insurance': 'When can I drop mortgage insurance?',
  'estimated-escrow': 'Which bills does my escrow account cover?',
  'estimated-total-monthly-payment': 'How could this payment change over time?',
  'estimated-taxes-insurance-assessments': 'How were the tax and insurance estimates made?',
  'estimated-closing-costs': 'Which of these fees can I shop for?',
  'estimated-cash-to-close': 'Could this number change before closing?',
  'closing-costs': 'Which fees changed from my Loan Estimate, and why?',
  'cash-to-close': 'How do I verify your wire instructions by phone before sending money? Wire fraud targets closings.',
  points: 'What would my rate be with zero points?',
  'application-fee': 'Can this fee be reduced or waived?',
  'underwriting-fee': 'What does underwriting include?',
  'appraisal-fee': 'When will I receive my copy of the appraisal?',
  'flood-determination-fee': 'Is this property in a flood zone?',
  'pest-inspection-fee': 'Can I see the list of approved providers for the services I can shop for?',
  'title-insurance-binder': 'Which title company is this estimate assuming?',
  'owners-title-policy': 'What happens if I skip the owner’s title policy?',
  'lender-credits': 'Are any lender credits available to offset my closing costs?',
  'le-j-total': 'Are any lender credits available to bring this total down?',
  'cd-f-total': 'Why are prepaids different from my estimate?',
  'cd-cash-total-closing-costs': 'Can you walk me through each line that changed from the Loan Estimate?',
  'homeowners-insurance-requirement': 'Do you have insurer requirements I should know about?',
  servicing: 'Who will service my loan after closing?',
  'partial-payments': 'What should I do if I ever cannot make a full payment?',
  apr: 'Why is my APR higher than my interest rate?',
  'appraised-prop-value': 'What happens to my loan terms if the appraisal comes in low?',
  'total-payoffs-payments': 'Which of my debts are being paid off through the loan, and what does each payoff quote include?',
});

/* One evergreen "Interesting fact" per field — regulatory history and mortgage
   mechanics, deliberately free of market statistics that drift. */
const FACTS = Object.freeze({
  'date-issued': 'Both forms exist because of the 2015 “Know Before You Owe” rule, which merged four overlapping federal disclosures into these two.',
  property: 'The loan is secured by a legal description of the property recorded in county land records — the street address is just its everyday name.',
  'sale-price': 'If the appraisal comes in below the sale price, the loan is sized from the lower of the two — one reason appraisal contingencies exist.',
  applicants: 'Federal rules define a complete “application” as just six items: name, income, Social Security number, property address, estimated value, and loan amount.',
  'closing-date': 'On a primary-home refinance, federal law adds a three-day right to cancel after signing — purchases have no such cooling-off period.',
  'disbursement-date': 'Refinance funds usually move days after signing because the rescission window must expire first; purchase funds typically move the same day.',
  'settlement-agent': 'Who runs a closing is regional custom: escrow companies out west, title agents in much of the country, and attorneys required in some states.',
  'file-number': 'Quoting the file number when you call the settlement agent is a simple defense against wire-fraud impostors who cannot supply it.',
  borrower: 'Being on the loan and being on the title are separate things — someone can own the home without owing the debt, and vice versa.',
  seller: 'The seller never signs the loan documents — their side of closing is entirely about transferring title and settling the money.',
  lender: 'The lender named here may sell the loan later, but the terms you signed travel with the loan and cannot change in a sale.',
  'mic-number': 'FHA assigns a case number to the PROPERTY as well as the borrower — a prior case on the same home can complicate a new one.',
  'loan-term': 'The 30-year fixed mortgage is largely an American invention — most countries offer far shorter fixed periods before the rate resets.',
  purpose: 'Refinances split into “rate and term” and “cash-out,” and the two are priced and underwritten differently.',
  product: 'Adjustable products are named by their structure — a 5/1 ARM is fixed for five years, then adjusts every year after.',
  'loan-type': 'Government programs differ in who backs the risk: FHA insures, VA guarantees, and conventional loans rely on private capital.',
  'loan-id': 'Under federal reporting rules, most mortgages also carry a universal loan identifier that follows them for life — even through sales between lenders.',
  'rate-lock': 'Rate locks are typically sold in 15-day increments — longer locks cost more because the lender is carrying more market risk for you.',
  'loan-amount': 'Loan amounts at or below the annually adjusted “conforming limit” can be bought by Fannie Mae and Freddie Mac — above it, the loan is jumbo.',
  'interest-rate': 'Mortgage rates move with the bond market — mostly tracking mortgage-backed securities, not the Federal Reserve’s headline rate directly.',
  'monthly-principal-interest': 'On a fully amortizing loan this number never changes, but the mix inside it flips over time from mostly interest to mostly principal.',
  'prepayment-penalty': 'After the Dodd-Frank reforms, prepayment penalties are rare and tightly capped — they cannot run past the third year of a loan.',
  'balloon-payment': 'Balloon structures helped fuel the 2008 crisis, and the “Qualified Mortgage” standard written afterward excludes them.',
  'projected-principal-interest': 'The table shows payment ranges by year precisely so adjustable and step loans cannot hide their future payments.',
  'projected-mortgage-insurance': 'The Homeowners Protection Act of 1998 gives conventional borrowers the right to cancel PMI at 20 percent equity — and forces it off at 22.',
  'estimated-escrow': 'Federal rules cap the cushion a servicer may keep in escrow at about two months of escrowed payments.',
  'estimated-total-monthly-payment': 'Lenders qualify you on this full housing payment — not just principal and interest — when they measure your debt-to-income ratio.',
  'estimated-taxes-insurance-assessments': 'Most “my payment went up” surprises are this line moving — a tax reassessment or insurance renewal, not the loan itself.',
  'property-taxes-property-cost': 'Property taxes are the oldest continuous tax in America, predating the income tax by more than a century.',
  'homeowners-insurance-property-cost': 'The lender can require coverage protecting the home, but choosing the insurer is legally your call.',
  'hoa-dues': 'HOA dues almost never run through escrow — missing them can still produce a lien on the home, which is why the form surfaces them.',
  'estimated-closing-costs': 'Closing costs fall into three federal “tolerance” buckets: fees that cannot rise at all, fees capped at 10 percent, and fees that float.',
  'closing-costs': 'If a zero-tolerance fee rises anyway, the lender owes you the difference back — refunds must arrive within 60 days of closing.',
  'borrower-paid-at-closing': 'The five payer columns were the big upgrade over the old HUD-1, which made who-paid-what genuinely hard to see.',
  'borrower-paid-before-closing': 'Fees on your card before closing — typically the appraisal — appear here so they are never collected twice.',
  'seller-paid-at-closing': 'Seller-paid items are still disclosed on your form because they shape the true economics of the deal you negotiated.',
  'seller-paid-before-closing': 'Even pre-paid seller items get a column — the form is designed to account for every dollar in the transaction.',
  'paid-by-others': 'This column often shows lender-paid or agent-paid items — proof that “no-cost” services are usually paid by someone.',
  points: 'One point is exactly one percent of the loan amount — the break-even question is how many months of rate savings repay that upfront cost.',
  'application-fee': 'Lenders may not charge anything beyond a credit-report fee before you receive the Loan Estimate and say you intend to proceed.',
  'underwriting-fee': 'Underwriters weigh the classic “four Cs” — credit, capacity, capital, and collateral.',
  'appraisal-fee': 'Since 2010, rules forbid loan officers from hand-picking the appraiser — orders flow through firewalls like appraisal management companies.',
  'credit-report-fee': 'Mortgage lenders typically pull all three bureaus at once — the “tri-merge” — and underwrite to the middle score.',
  'flood-determination-fee': 'Federal law has required flood insurance on federally backed loans in mapped flood zones since 1973.',
  'flood-monitoring-fee': 'FEMA redraws flood maps continually, so lenders pay to track whether a home gets mapped INTO a flood zone mid-loan.',
  'tax-monitoring-fee': 'Unpaid property taxes outrank the mortgage itself in a foreclosure — which is exactly why lenders pay to watch them.',
  'tax-status-research-fee': 'Tax records are checked back several years because tax liens survive a sale unless they are found and cleared.',
  'pest-inspection-fee': 'VA loans famously require a clear pest inspection in much of the country — termites cause billions in damage a year.',
  'survey-fee': 'Surveys regularly surface surprises — fences, driveways, and additions sitting on a neighbor’s land are classic title problems.',
  'title-insurance-binder': 'Title insurance is inverted insurance: one premium, no renewals, covering the PAST instead of the future.',
  'title-lenders-policy': 'The lender’s policy shrinks with the loan balance and dies at payoff — the owner’s policy is the one that protects your equity for life.',
  'title-settlement-agent-fee': 'The settlement agent is a fiduciary to BOTH sides — one of the few players at the table who does not work for either party alone.',
  'title-search': 'A title search walks the “chain of title” backward through decades of deeds, liens, divorces, and estates before insuring it.',
  'recording-fees': 'Recording acts date to the earliest American colonies — public notice of who owns what is one of the oldest functions of county government.',
  'transfer-taxes': 'Transfer taxes range from zero in some states to several percent of the price in a few cities — geography is everything.',
  'homeowners-insurance-premium': 'Lenders collect the first full year of coverage at closing so the home is never uninsured on day one.',
  'mortgage-insurance-premium': 'FHA’s upfront premium is usually financed into the loan itself — most borrowers never write a check for it.',
  'prepaid-interest': 'Closing late in the month shrinks this line — that is the entire trick behind “close at month-end” advice.',
  'prepaid-property-taxes': 'Whether taxes are due at closing depends on the local tax calendar — some closings prepay months, others almost nothing.',
  'homeowners-insurance-escrow': 'The escrow deposit is sized month by month so the account lands exactly at the legal cushion when bills come due.',
  'mortgage-insurance-escrow': 'Monthly MI flows through escrow like taxes and insurance — one payment, several destinations.',
  'property-taxes-escrow': 'Servicers re-run the escrow math annually; surpluses over $50 must be refunded to you by law.',
  'owners-title-policy': 'Buying the owner’s policy together with the lender’s usually triggers a steep “simultaneous issue” discount.',
  'lender-credits': 'Lender credits are simply negative points — the same rate-versus-cash trade running in the opposite direction.',
  'aggregate-adjustment': 'This line exists purely to obey the federal escrow-cushion cap — it is the only line on the form that is pure arithmetic.',
  'hoa-capital-contribution': 'Many associations charge new owners a reserve contribution — often a multiple of monthly dues — to fund future repairs.',
  'hoa-processing-fee': 'Association estoppel and transfer paperwork is one of the few closing costs with no federal tolerance protection at all.',
  'home-inspection-fee': 'Inspections are for YOU; appraisals are for the lender — skipping the first to save money protects nobody.',
  'home-warranty-fee': 'Home warranties are service contracts, not insurance — they are regulated differently and read very differently.',
  'seller-broker-commission': 'Real estate commissions appearing on the Closing Disclosure gained new significance after the 2024 industry settlement changed how buyer-broker pay is negotiated.',
  'buyer-broker-commission': 'Since the 2024 NAR settlement, buyer-broker compensation is explicitly negotiable and agreed in writing before touring homes.',
  'le-a-total': 'Section A is the zero-tolerance bucket — these lender charges legally cannot grow between estimate and closing.',
  'le-b-total': 'Section B services carry a combined 10 percent tolerance — the group total, not each line, is what may grow.',
  'le-c-total': 'Pick a provider from the lender’s written list and the 10 percent cap protects you; go off-list and the cap disappears.',
  'le-d-total': 'Section D is the cleanest single number for comparing what two lenders actually charge to make the same loan.',
  'le-e-total': 'Recording fees get the 10 percent cap, while transfer taxes get zero tolerance — two government fees, two different protections.',
  'le-f-total': 'Prepaids are not lender revenue at all — they are your own future obligations, paid early.',
  'le-g-total': 'The starting escrow deposit varies with your closing date — the same house closes with different escrow math in March than in November.',
  'le-h-total': 'Section H is where optional items live — by rule, anything truly optional must be labeled that way.',
  'le-i-total': 'Sections E through H can dwarf the lender’s own fees — most closing-cost sticker shock lives here, not in Section A.',
  'le-j-total': 'Comparing Section J across lenders only works with same-day quotes — prepaids and rate pricing both move daily.',
  'le-d-plus-i': 'D + I exists so you can see total costs BEFORE lender credits — the gross price of the deal, not the net.',
  'cd-a-total': 'If this total exceeds the Loan Estimate’s Section A, the lender owes you the difference — no exceptions without a valid changed circumstance.',
  'cd-b-total': 'Small pass-through differences are normal here; a big jump should come with a documented “changed circumstance.”',
  'cd-c-total': 'Fees here changed freely if you picked your own providers — the trade-off for the right to shop.',
  'cd-d-total': 'Final loan costs are the number to hold against Section D of your estimate — the comparison the form was built for.',
  'cd-loan-costs-subtotals': 'The subtotal row is bookkeeping that makes page 3’s did-it-change table possible.',
  'cd-e-total': 'Transfer taxes rising from the estimate is a zero-tolerance violation — one of the clearest refund triggers in the rule.',
  'cd-f-total': 'Prepaid interest is set by your actual closing date, so this section almost never matches the estimate to the penny.',
  'cd-g-total': 'Your escrow account starts life funded to a formula — the annual escrow analysis letter you will get each year re-runs it.',
  'cd-h-total': 'Owner’s title insurance and home warranties land here — genuinely optional, and disclosed that way.',
  'cd-i-total': 'Sections E–I are mostly third-party and government money — the lender keeps little of what is in this half of the page.',
  'cd-other-costs-subtotals': 'Splitting other costs across payer columns is how seller concessions become visible on YOUR form.',
  'cd-j-total': 'This is the number to reconcile against page 3’s comparison table before you sign — every change should have an explanation.',
  'cd-closing-costs-subtotals': 'Across these columns, every dollar of cost in the deal is assigned to someone — nothing is allowed to float.',
  'le-cash-total-closing-costs': 'Cash to close starts from Section J — the two tables are deliberately chained so you can audit the math.',
  'closing-costs-financed': 'Rolling costs into the loan trades cash today for interest on those costs for up to 30 years.',
  'down-payment': 'Twenty percent down is a PMI threshold, not a requirement — conventional programs go as low as 3 percent down.',
  deposit: 'Earnest money sits in a neutral escrow account by rule — neither buyer nor seller may hold it themselves.',
  'funds-for-borrower': 'On cash-out refinances this line is the whole point — it is how the equity you are extracting reaches you.',
  'seller-credits': 'Loan programs cap seller contributions — “interested party contribution” limits — so credits cannot quietly inflate the price.',
  'adjustments-other-credits': 'Prorations live here: the seller repays you their share of the year’s taxes for the months they owned the home.',
  'estimated-cash-to-close': 'Federal rules require this money as verified, documented funds — large unexplained deposits are underwriting’s least favorite thing.',
  'cd-cash-total-closing-costs': 'The three-column layout — estimate, final, did it change — was borrowed from the best consumer-testing results in the TRID redesign.',
  'closing-costs-paid-before-closing': 'This subtraction is why paying the appraisal early never increases what you owe at the table.',
  'cd-closing-costs-financed': 'Financed costs raise the loan balance, not the closing check — the comparison keeps that trade visible.',
  'cd-down-payment': 'A changed down payment here usually traces to renegotiation or an appraisal — page 3 makes the movement impossible to miss.',
  'cd-deposit': 'Your earnest money finally comes home on this line — subtracted from what you owe at the table.',
  'cd-funds-for-borrower': 'When this line grows between estimate and closing on a refinance, your cash-out grew — verify it matches what you asked for.',
  'cd-seller-credits': 'Credits negotiated after inspections commonly appear only on the final form — one of the happier reasons the numbers change.',
  'cd-adjustments-other-credits': 'This catch-all is audited like everything else on page 3 — every entry must tie to a documented adjustment.',
  'cash-to-close': 'Title companies verify wires by callback because closing funds are the single most-targeted wire in consumer banking.',
  'five-year-total-paid': 'The five-year horizon was chosen from consumer research — close to how long typical owners actually keep a loan before selling or refinancing.',
  'five-year-principal-paid': 'On a fresh 30-year loan, well under a tenth of the balance is repaid in the first five years — amortization front-loads interest.',
  apr: 'The APR was born in the Truth in Lending Act of 1968 — the first federal law to force lenders onto one comparable price measure.',
  tip: 'The Total Interest Percentage is the youngest number on the form — invented by the 2015 TRID rule itself.',
  appraisal: 'Your right to the appraisal comes from ECOA: a free copy, promptly, and no later than three business days before closing.',
  refinance: 'Serial refinancing resets amortization each time — a new 30-year clock means starting over in the interest-heavy years.',
  assumption: 'FHA and VA loans are generally assumable — in a high-rate market, a seller’s low-rate assumable loan can be worth real money.',
  'late-payment': 'Most mortgages give a 15-day grace period — and payment history is the single heaviest factor in credit scoring.',
  'homeowners-insurance-requirement': 'If your coverage lapses, the lender may “force-place” insurance — far costlier and protecting only the lender.',
  servicing: 'Servicing rights are traded constantly; federal law requires advance notice of a transfer and a 60-day grace period against misdirected payments.',
  'demand-feature': 'Nearly every mortgage has a due-on-sale clause, but a true demand feature — repayment on the lender’s whim — is rare and worth refusing.',
  'negative-amortization': 'The “pick-a-payment” loans at the center of 2008 were negative-amortization products — Qualified Mortgages now exclude them entirely.',
  'partial-payments': 'Held partial payments sit in “suspense” earning you nothing and stopping nothing — late fees can accrue until a full payment exists.',
  'security-interest': 'Depending on your state you signed a mortgage or a deed of trust — the difference decides whether foreclosure goes through a courtroom.',
  'loan-officer-contact': 'Every loan officer’s NMLS number is searchable at nmlsconsumeraccess.org — license history, employers, and public actions.',
  'lender-contact': 'Verify contact details against NMLS Consumer Access rather than an email signature — impostor emails are the classic wire-fraud opening.',
  'mortgage-broker-contact': 'About a third of American mortgages start with an independent broker — when one is involved, this column identifies them.',
  'buyer-broker-contact': 'Buyer representation only became standard in the 1990s — for most of history, every agent in the deal legally worked for the seller.',
  'seller-broker-contact': 'The seller’s broker owes you honesty but not loyalty — their fiduciary duty runs to the seller alone.',
  'settlement-agent-contact': 'This is the number to call — from a source you trust, not an email — before wiring a single dollar.',
  'confirm-receipt': 'The signature line says receipt is not acceptance in plain words because consumer testing showed people feared signing meant committing.',
  'cd-k-total': 'Sections K through N descend directly from the old HUD-1 settlement statement’s ledger — the oldest DNA on the form.',
  'borrower-transaction-sale-price': 'The ledger begins with the price, and every other line is an adjustment orbiting it.',
  'borrower-personal-property': 'Convey the washer and dryer in the sales contract, not the loan — lenders finance real property, not appliances.',
  'borrower-closing-costs-paid-at-closing': 'Page 2’s bottom line re-enters the ledger here — the form never asks you to trust a number twice.',
  'borrower-hoa-dues': 'Dues are prorated to the day — own the home for a third of the month, owe a third of the dues.',
  'cd-l-total': 'Section L is everything working in your favor — the loan itself is “paid on your behalf” in ledger terms.',
  'borrower-deposit': 'Your earnest money spent the escrow period in a trust account — this line is where it finally counts.',
  'borrower-transaction-loan-amount': 'The largest credit in the ledger is borrowed — a framing that keeps the true structure of the purchase honest.',
  'borrower-existing-loans': 'Loan assumptions were common in the early 1980s when rates hit historic highs — high-rate eras revive them.',
  'borrower-seller-credit': 'A seller credit is often the cash equivalent of a repair list — money instead of promises before closing.',
  'title-rebate': 'Rebates like this must be disclosed openly — RESPA has banned hidden referral kickbacks in settlement services since 1974.',
  'borrower-city-taxes': 'Tax prorations follow local law and custom — some regions pay taxes ahead, others behind, and the ledger absorbs both.',
  'total-due-from-borrower': 'The ledger’s two totals face each other like a balance sheet — closing is, at heart, an accounting exercise.',
  'total-paid-for-borrower': 'Everything already working for you, in one number — the counterweight to everything you owe.',
  'borrower-cash-to-close': 'When credits exceed charges — common in refinances — this line flips and the table pays YOU.',
  'cd-m-total': 'The seller’s ledger mirrors yours line for line — one transaction, two perspectives, identical arithmetic.',
  'seller-sale-price': 'The same price that tops your ledger tops the seller’s — as a credit instead of a charge.',
  'seller-personal-property': 'Separately priced personal property is itemized so loan collateral and household goods never blur.',
  'seller-hoa-dues': 'Whichever party prepaid the dues gets made whole — proration is the ledger’s fairness mechanism.',
  'cd-n-total': 'Section N is why sellers net far less than the sale price — payoffs, commissions, and credits all come out here.',
  'excess-deposit': 'This line exists for the rare deal where the deposit outgrew what the ledger needs — the overflow goes back where it belongs.',
  'seller-closing-costs': 'Commissions traditionally live in the seller’s column — the single largest closing cost in most transactions.',
  'first-mortgage-payoff': 'Payoff quotes accrue interest per day and expire — closings are timed against the quote’s good-through date.',
  'second-mortgage-payoff': 'Every lien must clear at closing for you to take clean title — HELOCs also need their credit lines formally frozen and closed.',
  'seller-credit-debit': 'The same credit appears once in your ledger and once in the seller’s — double-entry bookkeeping, alive and well at closing.',
  'seller-city-taxes': 'The seller’s share of the year’s taxes transfers here — calculated to the exact day of closing.',
  'total-due-to-seller': 'Gross proceeds before the deductions — the number sellers remember, before the one they actually receive.',
  'total-due-from-seller': 'Everything the seller owes at closing, netted in one place — the mirror of your Section L.',
  'cash-to-seller': 'Sale price minus payoffs, commissions, prorations, and credits — the seller’s real bottom line.',
  'escrow-account': 'Escrow is centuries-old trust mechanics: a neutral third party holding value until obligations are met — your servicer plays that role monthly.',
  'escrowed-property-costs': 'Roughly speaking, escrow turns two or three big annual bills into twelve predictable monthly slices.',
  'non-escrowed-property-costs': 'HOA dues are the classic non-escrowed cost — the servicer never sees them, but a lien can still follow if they lapse.',
  'initial-escrow-payment': 'The deposit is computed backward from each bill’s due date — which is why identical houses can close with different escrow checks.',
  'monthly-escrow-payment': 'Your monthly payment quietly funds a mini savings account audited annually under federal rules.',
  'no-escrow': 'Waiving escrow usually requires strong equity and often carries a pricing adjustment — lenders charge for the added risk.',
  'future-escrow-changes': 'The annual escrow analysis letter is the one piece of servicer mail worth actually reading — it explains every payment change.',
  'total-payments': 'Seeing three decades of payments as one number is sobering by design — long loans multiply small rate differences enormously.',
  'finance-charge': 'The finance charge is TILA’s original 1968 headline number — the total price of borrowing, in dollars.',
  'amount-financed': 'Amount financed is smaller than the loan amount because prepaid finance charges are subtracted — it is an APR input, not your balance.',
  'contract-details': 'The note and security instrument outrank every disclosure — disclosures describe the deal; those documents ARE the deal.',
  'liability-after-foreclosure': 'States split into recourse and non-recourse regimes — whether a shortfall can follow you depends on where the home sits.',
  'tax-deductions': 'Since the 2017 tax law, mortgage interest is deductible only on acquisition debt up to federal caps — and only if you itemize.',
  'questions-cfpb': 'The CFPB’s complaint database is public — companies answer on the record, and researchers mine it for industry patterns.',
  'estimated-prop-value': 'If the appraisal later comes in different from this estimate, a revised Loan Estimate can follow — value is a classic “changed circumstance.”',
  'appraised-prop-value': 'A refinance has no sale price to check value against — the appraisal alone does the job that market negotiation does in a purchase.',
  'payoffs-and-payments': 'Debts paid off here do not disappear — they move into the mortgage, trading unsecured balances for debt secured by your home for up to 30 years.',
  'total-payoffs-payments': 'When payoffs outgrow the new loan, a refinance flips from cash-out to cash-in — the exact scenario CFPB sample H-25(G) exists to illustrate.',
});

const groupedItems = [
  ['form-general-information', [
    ['date-issued', 'Date Issued', 'The day the creditor delivered this form or put it in the mail. For a Closing Disclosure, that date matters: you must receive it at least three business days before closing so you have time to review and question everything.'],
    ['property', 'Property', 'The address of the real estate securing the mortgage. Check it against your contract character by character — this is the property the lender can foreclose on if the loan is not repaid.'],
    ['sale-price', 'Sale Price', 'The contract price of the home itself, separate from any personal property priced on its own. It should match your purchase agreement exactly on both forms.'],
  ]],
  ['le-general-information', [
    ['applicants', 'Applicants', 'Everyone applying for the mortgage, with the mailing address tied to the application. Each applicant’s credit and income are considered in the approval.'],
  ]],
  ['cd-general-information', [
    ['closing-date', 'Closing Date', 'The day you sign and become legally obligated on the loan — the moment the rulebook calls consummation.'],
    ['disbursement-date', 'Disbursement Date', 'The day the loan and closing funds are actually expected to be paid out to you, the seller, or other parties. It can fall after the closing date, especially on refinances.'],
    ['settlement-agent', 'Settlement Agent', 'The neutral company running the closing and moving the money between the parties.'],
    ['file-number', 'File Number', 'The settlement agent’s reference number for your closing file. Use it to match documents and conversations to the transaction.'],
    ['borrower', 'Borrower', 'The consumer or consumers legally obligated on the mortgage, with the address the final disclosure associates with them.'],
    ['seller', 'Seller', 'The person or people transferring the property to you, with the address the form associates with them.'],
    ['lender', 'Lender', 'The creditor actually extending the mortgage credit shown on this Closing Disclosure.'],
    ['mic-number', 'Mortgage Insurance Case Number', 'The identifier a mortgage insurer or government insurance program assigns when the loan carries that coverage. Blank when none applies.'],
  ]],
  ['loan-information', [
    ['loan-term', 'Loan Term', 'How long you have to repay — 30 years on this fixed-rate sample. Longer terms mean lower payments but more total interest over the life of the loan.'],
    ['purpose', 'Loan Purpose', 'Why you are borrowing: a purchase, refinance, construction loan, or home-equity transaction.'],
    ['product', 'Loan Product', 'The loan’s rate structure. Fixed Rate means the interest rate never changes; adjustable and step products change how principal or interest is paid over time.'],
    ['loan-type', 'Loan Type', 'The loan program: Conventional means not government-backed, versus FHA, VA, or another listed program with different requirements and costs.'],
    ['loan-id', 'Loan ID', 'The creditor’s identifier for this application. Quote it in every conversation about the loan so nothing gets matched to the wrong file.'],
  ]],
  ['le-rate-lock', [
    ['rate-lock', 'Rate Lock', 'Whether your interest rate is locked. If it says NO, the rate and points can change at any time before you lock; the estimated closing costs themselves are good for ten business days from this form.'],
  ]],
  ['loan-terms', [
    ['loan-amount', 'Loan Amount', 'The principal you are scheduled to repay — before interest and the other costs of getting the mortgage. On the Closing Disclosure it should match your estimate unless you agreed to a change.'],
    ['interest-rate', 'Interest Rate', 'The yearly cost of borrowing as a percentage of the unpaid principal. It does not include fees — that broader number is the APR, so the two are never the same thing.'],
    ['monthly-principal-interest', 'Monthly Principal and Interest', 'Your base monthly payment: repaying the loan plus its interest. Taxes, insurance, and any mortgage insurance come on top of this number.'],
    ['prepayment-penalty', 'Prepayment Penalty', 'A charge for paying the loan off early, during the window stated on the form. Many loans do not have one — this sample does, so it is worth asking whether it can be removed.'],
    ['balloon-payment', 'Balloon Payment', 'A large lump-sum payment due at the end of a loan that does not fully pay itself off through regular payments. Most borrowers are best served being cautious of loans that have one.'],
  ]],
  ['projected-payments', [
    ['projected-principal-interest', 'Projected Principal and Interest', 'The scheduled principal-and-interest portion of each payment for every period the table displays.'],
    ['projected-mortgage-insurance', 'Projected Mortgage Insurance', 'The monthly mortgage-insurance amount, shown with the year range when the table expects it to change or fall away. On conventional loans it can usually be removed once you build enough equity.'],
    ['estimated-escrow', 'Estimated Escrow', 'A monthly set-aside collected with your payment so the servicer can pay selected property costs — typically taxes and insurance — on your behalf.'],
    ['estimated-total-monthly-payment', 'Estimated Total Monthly Payment', 'Your real monthly cost for each period shown: principal, interest, mortgage insurance, and escrow added together.'],
    ['estimated-taxes-insurance-assessments', 'Estimated Taxes, Insurance, and Assessments', 'The estimated monthly total of selected property costs, whether they run through escrow or you pay them directly. Even escrowed amounts can rise year to year.'],
    ['property-taxes-property-cost', 'Property Taxes', 'Charges a state or local taxing authority places on the property. They may be collected through escrow or paid directly, and they can change with assessments.'],
    ['homeowners-insurance-property-cost', 'Homeowner’s Insurance Property Cost', 'The property cost for insurance coverage on the home, collected through escrow or paid directly to your insurer.'],
    ['hoa-dues', 'Homeowner’s Association Dues', 'Recurring charges owed to an association. They can appear here even when they are not part of your escrow account, because you still owe them monthly.'],
  ]],
  ['le-costs-at-closing', [
    ['estimated-closing-costs', 'Estimated Closing Costs', 'The estimated fees due at closing: projected loan costs plus other costs, minus any lender credits. Ask which of these you can shop for — that is where borrowers save real money.'],
  ]],
  ['cd-costs-at-closing', [
    ['closing-costs', 'Closing Costs', 'The final fee total: loan costs plus other costs minus lender credits. Some fees legally cannot increase from the Loan Estimate and others can rise only 10 percent, so compare the two forms.'],
  ]],
  ['payer-column', [
    ['borrower-paid-at-closing', 'Borrower-Paid at Closing', 'Charges you pay out of the funds handled at the closing table.'],
    ['borrower-paid-before-closing', 'Borrower-Paid Before Closing', 'Charges you already paid before closing day — an appraisal charged to your card, for example — so they are not collected again.'],
    ['seller-paid-at-closing', 'Seller-Paid at Closing', 'Charges the seller covers out of the funds handled at closing.'],
    ['seller-paid-before-closing', 'Seller-Paid Before Closing', 'Charges the seller paid before the closing funds are disbursed.'],
    ['paid-by-others', 'Paid by Others', 'Charges covered by someone other than you or the seller — a lender, an agent, or another party.'],
  ]],
  ['cost-item', [
    ['points', 'Points', 'Money paid up front to buy a lower interest rate, disclosed as a percentage of the loan and a dollar amount. Points are optional — a zero-point loan simply carries a somewhat higher rate.'],
    ['application-fee', 'Application Fee', 'The lender’s charge for accepting and processing your application. Because the lender sets it, it is sometimes negotiable.'],
    ['underwriting-fee', 'Underwriting Fee', 'The lender’s charge for evaluating your application, the property, and the loan file against its approval standards.'],
    ['appraisal-fee', 'Appraisal Fee', 'Pays a licensed appraiser to give an independent opinion of the home’s value. The lender picks the appraiser, and you are entitled to a copy of the report.'],
    ['credit-report-fee', 'Credit Report Fee', 'Covers pulling the credit reports and scores used in underwriting. Small pass-through differences from the estimate are normal.'],
    ['flood-determination-fee', 'Flood Determination Fee', 'Covers checking whether the property sits in a mapped flood zone where flood insurance may be required.'],
    ['flood-monitoring-fee', 'Flood Monitoring Fee', 'Pays for ongoing monitoring in case the property’s flood-zone status changes during the life of the loan.'],
    ['tax-monitoring-fee', 'Tax Monitoring Fee', 'Pays a service to watch that property taxes on the home get paid on time.'],
    ['tax-status-research-fee', 'Tax Status Research Fee', 'Covers researching and confirming the property’s tax payment status and history for the transaction.'],
    ['pest-inspection-fee', 'Pest Inspection Fee', 'Pays for an inspection for termites and other wood-destroying organisms. It lives in the shoppable section, where comparing providers can genuinely save money.'],
    ['survey-fee', 'Survey Fee', 'Pays for confirming the property’s boundary lines, improvements, and easements.'],
    ['title-insurance-binder', 'Title Insurance Binder', 'An interim title commitment describing the conditions under which the title policy will be issued. Title services are shoppable — comparing at least two companies is worth it.'],
    ['title-lenders-policy', 'Lender’s Title Policy', 'Title insurance protecting the lender against ownership disputes, up to the policy limits. It is required — and it does not protect you; the optional owner’s policy does that.'],
    ['title-settlement-agent-fee', 'Title Settlement Agent Fee', 'Pays the company that coordinates, documents, and completes your closing.'],
    ['title-search', 'Title Search', 'Research into the property’s ownership history in the public records, hunting for liens, claims, and restrictions before you take title.'],
    ['recording-fees', 'Recording Fees', 'Government charges for entering the deed, mortgage, and related documents into the public land records.'],
    ['transfer-taxes', 'Transfer Taxes', 'State or local government charges tied to transferring the property or recording the change in ownership.'],
    ['homeowners-insurance-premium', 'Homeowner’s Insurance Premium', 'Your first homeowner’s insurance premium, paid in advance at closing for the policy period stated on the form.'],
    ['mortgage-insurance-premium', 'Mortgage Insurance Premium', 'An upfront mortgage-insurance charge collected at closing when the loan’s terms require that coverage.'],
    ['prepaid-interest', 'Prepaid Interest', 'Interest covering the days between closing and the start of your first regular payment period. The exact closing date sets this number, so it commonly shifts from the estimate.'],
    ['prepaid-property-taxes', 'Prepaid Property Taxes', 'Property taxes due at or near closing for a stated period — separate from the deposit that seeds your escrow account.'],
    ['homeowners-insurance-escrow', 'Homeowner’s Insurance Escrow', 'The initial deposit that seeds your escrow account so it can pay future insurance premiums when they come due.'],
    ['mortgage-insurance-escrow', 'Mortgage Insurance Escrow', 'The initial escrow deposit for future mortgage-insurance payments, when the loan collects that amount.'],
    ['property-taxes-escrow', 'Property Taxes Escrow', 'The initial deposit that seeds your escrow account so it can pay property-tax bills when they come due.'],
    ['owners-title-policy', 'Owner’s Title Policy', 'Optional title insurance protecting YOUR ownership of the home, subject to the policy’s terms and limits. It is a one-time cost that many buyers consider worthwhile.'],
    ['lender-credits', 'Lender Credits', 'Money the creditor applies to reduce your closing costs, often in exchange for a somewhat higher rate. A useful lever when cash at closing is tight.'],
    ['aggregate-adjustment', 'Aggregate Adjustment', 'A small calculation that keeps your initial escrow deposit within the legal limit once all the monthly cushions are combined.'],
    ['hoa-capital-contribution', 'HOA Capital Contribution', 'A payment into an association’s reserve or capital fund, charged when the property transfer requires it.'],
    ['hoa-processing-fee', 'HOA Processing Fee', 'The association’s administrative charge for paperwork connected with the ownership transfer.'],
    ['home-inspection-fee', 'Home Inspection Fee', 'Pays for the property-condition inspection you ordered in connection with the purchase.'],
    ['home-warranty-fee', 'Home Warranty Fee', 'Pays for a service contract covering specified home systems or appliances, under the contract’s own terms.'],
    ['seller-broker-commission', 'Seller’s Broker Commission', 'Compensation for the real estate broker on the seller’s side of the transaction, shown here so the full money picture is on one form.'],
    ['buyer-broker-commission', 'Buyer’s Broker Commission', 'Compensation for the real estate broker on the buyer’s side of the transaction, disclosed alongside every other cost in the deal.'],
  ]],
  ['le-cost-total', [
    ['le-a-total', 'Estimated Origination Charges', 'Section A adds up what the lender itself charges to make the loan: points plus its own processing and underwriting fees.'],
    ['le-b-total', 'Estimated Services You Cannot Shop For', 'Section B totals required services where the lender picks the provider — you pay, but you do not choose.'],
    ['le-c-total', 'Estimated Services You Can Shop For', 'Section C totals required services where YOU may pick the provider. Shopping this section is one of the few ways to directly cut closing costs.'],
    ['le-d-total', 'Estimated Total Loan Costs', 'Section D adds origination charges and both service categories into total estimated loan costs.'],
    ['le-e-total', 'Estimated Taxes and Government Fees', 'Section E totals the estimated recording charges, transfer taxes, and other government fees.'],
    ['le-f-total', 'Estimated Prepaids', 'Section F totals amounts paid in advance — your first insurance premium, prepaid interest, and taxes due around closing.'],
    ['le-g-total', 'Estimated Initial Escrow Payment', 'Section G totals the deposits collected at closing to open your escrow account and give it a starting balance.'],
    ['le-h-total', 'Estimated Other Costs', 'Section H totals transaction costs that do not fit the tax, prepaid, or escrow categories — like an optional owner’s title policy.'],
    ['le-i-total', 'Estimated Total Other Costs', 'Section I adds government fees, prepaids, the initial escrow deposit, and other costs into one number.'],
    ['le-j-total', 'Estimated Total Closing Costs', 'Section J is the headline: loan costs plus other costs, minus general lender credits. Compare this line across Loan Estimates from different lenders.'],
    ['le-d-plus-i', 'Estimated D plus I', 'The D + I line shows loan costs plus other costs before lender credits are subtracted — the raw fee total.'],
  ]],
  ['cd-cost-total', [
    ['cd-a-total', 'Final Origination Charges', 'Section A totals the final points and lender charges. Origination charges legally cannot increase from your Loan Estimate.'],
    ['cd-b-total', 'Final Services Borrower Did Not Shop For', 'Section B totals final charges for required services where the lender chose the provider.'],
    ['cd-c-total', 'Final Services Borrower Did Shop For', 'Section C totals final charges for required services where you chose — or could have chosen — the provider. Fees you shopped for can change freely from the estimate.'],
    ['cd-d-total', 'Final Total Loan Costs', 'Section D totals the final borrower-paid origination and service charges from Sections A, B, and C.'],
    ['cd-loan-costs-subtotals', 'Loan Costs Subtotals', 'This line spreads the final loan costs across the borrower-paid timing columns before the total is shown.'],
    ['cd-e-total', 'Final Taxes and Government Fees', 'Section E totals the final recording charges, transfer taxes, and other government fees.'],
    ['cd-f-total', 'Final Prepaids', 'Section F totals the final prepaid amounts. These often move from the estimate because the exact closing date sets the prepaid interest.'],
    ['cd-g-total', 'Final Initial Escrow Payment', 'Section G totals the final deposits collected to open your escrow account.'],
    ['cd-h-total', 'Final Other Costs', 'Section H totals the final costs outside the tax, prepaid, and escrow categories — including any optional owner’s title policy you elected.'],
    ['cd-i-total', 'Final Total Other Costs', 'Section I totals the final borrower-paid government fees, prepaids, escrow deposit, and other costs.'],
    ['cd-other-costs-subtotals', 'Other Costs Subtotals', 'This line spreads the final other costs across the payer and timing columns before the borrower-paid total is shown.'],
    ['cd-j-total', 'Final Total Closing Costs', 'Section J is the final all-in total: borrower-paid loan costs and other costs after lender credits. Page 3 compares each category back to your estimate.'],
    ['cd-closing-costs-subtotals', 'Closing Costs Subtotals', 'This line spreads every final closing cost across the borrower, seller, timing, and paid-by-others columns.'],
  ]],
  ['le-cash', [
    ['le-cash-total-closing-costs', 'Estimated Total Closing Costs in Cash Table', 'This row carries the Section J fee total into the math that produces your estimated cash to close.'],
    ['closing-costs-financed', 'Estimated Closing Costs Financed', 'Closing costs expected to be rolled into the loan amount instead of paid from your own funds — you borrow them rather than bring them.'],
    ['down-payment', 'Estimated Down Payment or Funds from Borrower', 'The part of the purchase you pay yourself — essentially the sale price minus the loan amount.'],
    ['deposit', 'Estimated Deposit', 'The earnest money you already paid with your offer. It is subtracted here because it already counts toward what you owe.'],
    ['funds-for-borrower', 'Estimated Funds for Borrower', 'Loan or transaction funds expected to be paid out to you rather than into the purchase.'],
    ['seller-credits', 'Estimated Seller Credits', 'Money the seller has agreed to put toward your costs — often negotiated after inspections. Credits here directly reduce your cash to close.'],
    ['adjustments-other-credits', 'Estimated Adjustments and Other Credits', 'The catch-all row for other additions or credits that change how much cash you need at closing.'],
  ]],
  ['le-cash-total', [
    ['estimated-cash-to-close', 'Estimated Cash to Close', 'The bottom line of the estimate: what you are projected to bring to — or in some cases receive from — closing once every component is combined.'],
  ]],
  ['cd-cash', [
    ['cd-cash-total-closing-costs', 'Final Total Closing Costs Comparison', 'The heart of page 3: the estimated fee total next to the final one, with a flag for whether it changed and a pointer to the detail if it did.'],
    ['closing-costs-paid-before-closing', 'Closing Costs Paid Before Closing', 'Subtracts the closing costs you already paid before closing day, compared against what the estimate assumed.'],
    ['cd-closing-costs-financed', 'Final Closing Costs Financed', 'Compares the estimated and final closing costs rolled into the loan amount instead of paid in cash.'],
    ['cd-down-payment', 'Final Down Payment or Funds from Borrower', 'Compares the estimated and final down payment or other funds you are putting into the transaction.'],
    ['cd-deposit', 'Final Deposit', 'Compares the estimated and final earnest-money credit and subtracts it from the cash you must bring.'],
    ['cd-funds-for-borrower', 'Final Funds for Borrower', 'Compares the estimated and final amounts expected to be disbursed to you rather than into the purchase.'],
    ['cd-seller-credits', 'Final Seller Credits', 'Compares estimated and final seller contributions. Credits often appear or grow after inspections, and they lower your cash to close.'],
    ['cd-adjustments-other-credits', 'Final Adjustments and Other Credits', 'Compares the other estimated and final additions or credits affecting your closing amount.'],
  ]],
  ['cd-cash-total', [
    ['cash-to-close', 'Final Cash to Close', 'The exact amount to bring to closing — usually by wire or cashier’s check — once every final component is combined. Verify payment instructions independently before sending anything.'],
  ]],
  ['le-comparison', [
    ['five-year-total-paid', 'Total Paid in Five Years', 'Everything you are scheduled to pay in the first five years — principal, interest, mortgage insurance, and loan costs. A strong yardstick for comparing offers with different rates and fees.'],
    ['five-year-principal-paid', 'Principal Paid in Five Years', 'How much of the loan itself you will have paid down after five years. Early payments are mostly interest, so this number is smaller than most people expect.'],
  ]],
  ['shared-cost-measure', [
    ['apr', 'Annual Percentage Rate', 'Your cost of borrowing including certain fees, expressed as a yearly rate. It runs higher than the note rate because it counts loan costs — which is why offers are compared on APR, not rate alone.'],
    ['tip', 'Total Interest Percentage', 'The total interest you would pay over the full term, as a percentage of the loan amount. Around 69 percent here — roughly 69 cents of interest per borrowed dollar if the loan runs its whole course.'],
  ]],
  ['shared-other-disclosure', [
    ['appraisal', 'Appraisal', 'Your right to the appraisal: the lender must promptly give you a copy of the valuation report, even if the loan never closes.'],
    ['refinance', 'Refinance', 'A plain reminder that refinancing later is never guaranteed — it depends on your finances, the property’s value, and market conditions at that time.'],
  ]],
  ['shared-loan-disclosure', [
    ['assumption', 'Assumption', 'Whether a future buyer of your home could take over this loan on its original terms. Most conventional loans, including this sample, do not allow it.'],
    ['late-payment', 'Late Payment', 'The grace period and the formula for the late charge — here, a fee after a payment is more than fifteen days late, as set by the loan terms.'],
  ]],
  ['le-other-consideration', [
    ['homeowners-insurance-requirement', 'Homeowner’s Insurance Requirement', 'You must keep the property insured, but you may choose any insurer the lender reasonably accepts. Shopping that coverage each year is one of the easiest recurring savings in homeownership.'],
    ['servicing', 'Servicing', 'Who you will actually send payments to. Loans are routinely transferred to a servicer after closing — and your loan’s terms do not change when that happens.'],
  ]],
  ['cd-loan-disclosure', [
    ['demand-feature', 'Demand Feature', 'Whether the lender may demand full repayment early under conditions in the loan documents. “Does not have” is the answer most borrowers want to see.'],
    ['negative-amortization', 'Negative Amortization', 'When scheduled payments do not cover the interest due, so the unpaid interest is added to your balance and the loan grows while you pay. Approach any loan that has this with real caution.'],
    ['partial-payments', 'Partial Payments', 'What happens if you pay less than the full amount due. On this sample the servicer may hold partial payments unapplied until a full payment exists.'],
    ['security-interest', 'Security Interest', 'Identifies the property securing repayment — and warns plainly that failing to meet the loan obligations can put that property at risk.'],
  ]],
  ['le-contact', [
    ['loan-officer-contact', 'Loan Officer Contact', 'The individual handling your application, with their license number, email, and phone. This is your first call for every question on the form.'],
  ]],
  ['shared-lender-contact', [
    ['lender-contact', 'Lender Contact', 'The creditor’s name with its address, license numbers, representative, email, and phone. Verify contact details independently before wiring or sending anything.'],
  ]],
  ['cd-contact', [
    ['mortgage-broker-contact', 'Mortgage Broker Contact', 'The Mortgage Broker column stays visible, but its detail cells are blank in this rendered sample — no broker company or representative is provided here.'],
    ['buyer-broker-contact', 'Buyer’s Real Estate Broker Contact', 'The business and representative details for the real estate broker working the buyer’s side.'],
    ['seller-broker-contact', 'Seller’s Real Estate Broker Contact', 'The business and representative details for the real estate broker working the seller’s side.'],
    ['settlement-agent-contact', 'Settlement Agent Contact', 'The closing company’s business and representative details — the people to call with settlement questions.'],
  ]],
  ['receipt', [
    ['confirm-receipt', 'Confirm Receipt', 'Signing here only confirms you RECEIVED the form. It does not accept the loan, and it does not obligate you to close.'],
  ]],
  ['borrower-transaction', [
    ['cd-k-total', 'Due from Borrower at Closing', 'Section K totals everything you owe: the purchase price, your closing costs, and other amounts charged to you at closing.'],
    ['borrower-transaction-sale-price', 'Borrower Transaction Sale Price', 'The contract price of the home, entered on your side of the ledger as the largest amount you owe.'],
    ['borrower-personal-property', 'Borrower Transaction Personal Property', 'Any separately agreed price for tangible personal property — appliances, furniture — included in the sale.'],
    ['borrower-closing-costs-paid-at-closing', 'Borrower Closing Costs Paid at Closing', 'Carries your borrower-paid-at-closing costs from Section J into the transaction ledger.'],
    ['borrower-hoa-dues', 'Borrower HOA Dues Adjustment', 'Splits association dues for the stated period fairly between you and the seller, based on the closing date.'],
    ['cd-l-total', 'Paid Already by or on Behalf of Borrower', 'Section L totals everything already credited to you: your deposit, the loan amount, seller credits, and other amounts paid on your behalf.'],
    ['borrower-deposit', 'Borrower Deposit', 'Your earnest money, already paid with the offer, now credited against what you owe.'],
    ['borrower-transaction-loan-amount', 'Loan Amount Applied for Borrower', 'The mortgage principal itself, applied as a credit toward everything due at closing.'],
    ['borrower-existing-loans', 'Existing Loans Assumed by Borrower', 'The balance of an existing loan you are assuming or taking subject to, credited on your side when that applies.'],
    ['borrower-seller-credit', 'Seller Credit to Borrower', 'The seller’s agreed contribution, credited to you and reducing the cash you must bring.'],
    ['title-rebate', 'Title Company Rebate', 'A rebate from the named title company, applied as an other credit in your ledger.'],
    ['borrower-city-taxes', 'Borrower City or Town Taxes Adjustment', 'Credits or charges city or town taxes for the stated period so each party pays only for the days they own the home.'],
    ['total-due-from-borrower', 'Total Due from Borrower', 'Repeats the Section K total — everything you owe before your credits in Section L are subtracted.'],
    ['total-paid-for-borrower', 'Total Paid for Borrower', 'Repeats the Section L total — the credits subtracted from what you owe.'],
    ['borrower-cash-to-close', 'Borrower Cash to Close', 'The difference between what you owe and what is already credited, labeled to show whether cash comes from you or goes to you.'],
  ]],
  ['seller-transaction', [
    ['cd-m-total', 'Due to Seller at Closing', 'Section M totals what the seller is owed: the property price plus other amounts credited to the seller.'],
    ['seller-sale-price', 'Seller Transaction Sale Price', 'The contract price of the home, entered on the seller’s side as the largest amount owed to them.'],
    ['seller-personal-property', 'Seller Transaction Personal Property', 'Any separately agreed price for personal property included in the sale, credited to the seller.'],
    ['seller-hoa-dues', 'Seller HOA Dues Adjustment', 'Splits association dues for the stated period between the seller and buyer, based on the closing date.'],
    ['cd-n-total', 'Due from Seller at Closing', 'Section N totals what the seller owes: their closing costs, mortgage payoffs, credits to you, and other charges.'],
    ['excess-deposit', 'Excess Deposit', 'The part of a buyer deposit beyond what the ledger already accounts for, due back from the seller when it applies.'],
    ['seller-closing-costs', 'Seller Closing Costs', 'Carries the seller-paid-at-closing costs from Section J into the seller’s side of the ledger.'],
    ['first-mortgage-payoff', 'First Mortgage Payoff', 'The amount used at closing to pay off the seller’s first mortgage so you receive clear title.'],
    ['second-mortgage-payoff', 'Second Mortgage Payoff', 'The amount used at closing to satisfy a second mortgage on the property, when one exists.'],
    ['seller-credit-debit', 'Seller Credit Charged to Seller', 'The seller contribution charged on the seller’s side — the same credit that appears on your side of the ledger.'],
    ['seller-city-taxes', 'Seller City or Town Taxes Adjustment', 'Allocates city or town taxes for the stated period to the seller’s side of the ledger.'],
    ['total-due-to-seller', 'Total Due to Seller', 'Repeats the Section M total credited to the seller before their charges are subtracted.'],
    ['total-due-from-seller', 'Total Due from Seller', 'Repeats the Section N total subtracted from what the seller is owed.'],
    ['cash-to-seller', 'Cash to Seller', 'The seller’s bottom line: credits minus charges, labeled to show whether cash goes to or comes from the seller.'],
  ]],
  ['escrow', [
    ['escrow-account', 'Escrow Account', 'Confirms the loan will have an escrow account: part of each payment is held so the servicer can pay listed property costs for you when they come due.'],
    ['escrowed-property-costs', 'Escrowed Property Costs', 'The estimated first-year costs — typically taxes and insurance — that the escrow account is expected to pay on your behalf.'],
    ['non-escrowed-property-costs', 'Non-Escrowed Property Costs', 'Estimated first-year property expenses you must pay directly, because the escrow account does not cover them.'],
    ['initial-escrow-payment', 'Initial Escrow Payment', 'The amount collected at closing to open the account and give it a starting balance, including any allowed cushion.'],
    ['monthly-escrow-payment', 'Monthly Escrow Payment', 'The slice of your regular mortgage payment that goes into escrow for property costs.'],
    ['no-escrow', 'No Escrow', 'When a loan has no escrow account, this area explains your direct-payment responsibilities and any fee for waiving escrow.'],
    ['future-escrow-changes', 'Future Escrow Changes', 'A heads-up that property costs — and therefore escrow payments — can change, plus the consequences of canceling escrow or missing property-cost bills.'],
  ]],
  ['loan-calculation', [
    ['total-payments', 'Total of Payments', 'Everything you are scheduled to pay over the full term: principal, interest, mortgage insurance, and borrower-paid loan costs combined.'],
    ['finance-charge', 'Finance Charge', 'The total dollar cost of the credit under Regulation Z’s finance-charge rules — all the interest plus the counted loan fees over the full term.'],
    ['amount-financed', 'Amount Financed', 'The loan amount available after subtracting the upfront finance charges — the figure federal APR math is built on, not necessarily the cash you see.'],
  ]],
  ['other-disclosure', [
    ['contract-details', 'Contract Details', 'Points you to your note and security instrument for the rules on default, acceleration, foreclosure, and early repayment.'],
    ['liability-after-foreclosure', 'Liability after Foreclosure', 'Whether state law may protect you from owing a remaining balance after a foreclosure — protections differ meaningfully from state to state.'],
    ['tax-deductions', 'Tax Deductions', 'A caution that interest on debt above the property’s value may not be federally deductible, with a pointer to consult a tax advisor about your situation.'],
  ]],
  ['questions', [
    ['questions-cfpb', 'Questions and CFPB Contact', 'Directs questions about the loan’s terms or costs to the listed contacts, and gives the CFPB’s mortgage-closing resources and complaint line.'],
  ]],
  ['refi-property-value', [
    ['estimated-prop-value', 'Estimated Property Value', 'The value the lender is using for the home on a refinance estimate. With no sale price in the deal, this estimate anchors the loan-to-value math instead.'],
    ['appraised-prop-value', 'Appraised Property Value', 'The appraised value of the home used for the final refinance numbers. Loan-to-value — and with it, whether mortgage insurance is required — is measured against this figure.'],
  ]],
  ['refi-payoffs', [
    ['payoffs-and-payments', 'Payoffs and Payments', 'The itemized list of who gets paid out of your new loan — the old mortgage first, then any liens, credit cards, or other debts you chose to roll in.'],
    ['total-payoffs-payments', 'Total Payoffs and Payments', 'The combined amount of the new loan spent paying off existing loans and other debts. Set against the loan amount, it decides whether cash comes to you or from you at closing.'],
  ]],
];

const items = groupedItems.flatMap(([group, entries]) => entries.map(entry => [...entry, group]));

export const EXPLANATIONS = Object.freeze(Object.fromEntries(items.map(([id, title, what, groupName]) => {
  const group = GROUPS[groupName];
  const fact = FACTS[id];
  if (!fact) throw new TypeError(`missing interesting fact for explanation: ${id}`);
  const record = {
    id,
    title,
    body: `${what} ${group.why} ${fact} ${SAMPLE_NOTE}`,
    /* The approved sentences split into the decoder card's flips. */
    cards: Object.freeze([
      Object.freeze({ heading: 'Quick definition', text: what }),
      Object.freeze({ heading: 'In practice', text: group.why }),
      Object.freeze({ heading: 'Interesting fact', text: fact }),
      Object.freeze({ heading: 'Source guide', text: SAMPLE_NOTE }),
    ]),
    source: Object.freeze({
      type: 'CFPB samples, Guide to Forms v2.1, and Regulation Z',
      reference: group.reference,
    }),
    review: Object.freeze({ status: 'approved', reviewer: 'Zachary Zink', reviewedOn: '2026-08-31' }),
  };
  if (ASKS[id]) record.learnerQuestion = ASKS[id];
  return [id, Object.freeze(record)];
})));
